apiVersion: v1
kind: Pod
metadata:
  name: 2pods-shared-vol
spec:
  containers:
  - image: supergiantkir/animals:bear
    imagePullPolicy: IfNotPresent
    name: app1 
    command: [    'sh', '-c', 'echo Container 1 myapp ; sleep 3600']
    volumeMounts:
    - mountPath: /storage
      name: test-volume
  - image: yanivomc/spring-music:latest
    imagePullPolicy: IfNotPresent
    name: app2
    command: [    'sh', '-c', 'echo Container 2 myapp ; sleep 3600']
    volumeMounts:
    - mountPath: /storage
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path:  /tmp/files 
      # this field is optional
      type: DirectoryOrCreate
